### ISSUE TITLE
Connection types?

### ISSUE THREAD

**Issue by knpwrs** [graphql/swapi-graphql#114]
I was wondering if there was a specific reason as to why there are connection types. For instance, consider the following query:

```graphql
{
  person(personID: 1) {
    filmConnection {
      films {
        title
      }
    }
  }
}
```

It would seem more intuitive to me to have something like the following:

```graphql
{
  person(personID: 1) {
    films {
      title
    }
  }
}
```

The latter is how I recently constructed a graphql schema of my own, so I was wondering what the motivation was behind the connection types.

**Comment by wincent** [comment]
In practice, the API doesn't do either one of those but rather:

```graphql
{
  person(...) {
    filmConnection(first: 10) {
      edges {
        cursor
        node {
          title
        }
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}
```

The connection convention (and it is only a convention) has proved to be useful at Facebook because it gives us a way to explicitly model edge relationships in the graph (edges are a useful place to store metadata about the relationship), and the structure around cursors and `pageInfo` allows us to build flexible and powerful pagination strategies that have been useful in our products (examples: news feed case with non-trivial ranking mechanisms, "head" loads, "tail" loads, dealing with "necks" and "gaps", handling "pull to refresh" scenarios etc). It also means that tools like Relay can offer useful out-of-the-box pagination handling for any schema that follows the convention.

I'm going to close this, but let us know if you have any more questions.

**Comment by knpwrs** [comment]
Gotcha, that makes perfect sense. Though it is worth noting what while you said, "the API doesn't do either one of those," my first query actually works on the SWAPI demo:

[![image](https://user-images.githubusercontent.com/174864/28494235-2d63e108-6ef6-11e7-82bf-ac08db08be56.png)](http://graphql.org/swapi-graphql/?query=%7B%0A%20%20person(personID%3A%201)%20%7B%0A%20%20%20%20filmConnection%20%7B%0A%20%20%20%20%20%20films%20%7B%0A%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

Your example query _also_ works:

[![image](https://user-images.githubusercontent.com/174864/28494240-515121b6-6ef6-11e7-8e0d-b992a6e01bd6.png)](http://graphql.org/swapi-graphql/?query=%7B%0A%20%20person(personID%3A%201)%20%7B%0A%20%20%20%20filmConnection(first%3A%2010)%20%7B%0A%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20cursor%0A%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

**Comment by wincent** [comment]
Whoops, I didn't know we had a `films` field. I just assumed we didn't, because that kind of field (which bypasses/hides `edges`) is discouraged internally.
